# How to create scalar, Vector, matrix and Tensor using Numpy

In [ ]:
import numpy as np

In [ ]:
scalar = np.array(5)

In [ ]:
scalar.dtype

dtype('int64')

In [ ]:
scalar.ndim

0

In [ ]:
vector = np.array([1,2])

In [ ]:
vector

array([1, 2])

In [ ]:
vector.ndim

1

In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix.ndim

2

In [ ]:
tensor = np.array([[[1,2,3],
                    [4,5,6]]])

In [ ]:
tensor

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
tensor.ndim

3

# How to create scalar, Vector, matrix and Tensor using Pytorch

In [ ]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 55.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 33.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 40.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 79.7 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [ ]:
import torch as tc

In [ ]:
scalar = tc.tensor(5)

In [ ]:
scalar

tensor(5)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.dtype

torch.int64

In [ ]:
vector = tc.tensor([2,4])

In [ ]:

vector

tensor([2, 4])

In [ ]:
vector.ndim

1

In [ ]:
matrix = tc.tensor([[1,2,3],
                    [4,5,6]])

In [ ]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
matrix.ndim

2

In [ ]:
Tensor = tc.tensor([[[1,2,3,4],
                     [5,6,7,8]]])

In [ ]:
Tensor

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.size()

torch.Size([1, 2, 4])

In [ ]:
Tensor[0]

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

**Random tensors**

**Why random tensors?**

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

# How to create random tensor using numpy array ?

In [ ]:
#create random numpy array size (2,3)

arr = np.random.rand(2,3)

In [ ]:
arr

array([[0.23612929, 0.61902847, 0.52647498],
       [0.9244111 , 0.44780498, 0.69973423]])

In [ ]:
arr1 = np.random.rand(5)

In [ ]:
arr1

array([0.16214135, 0.25713948, 0.78788525, 0.07850428, 0.49152857])

In [ ]:
arr_int = np.random.randint(45, size = (3,4))

In [ ]:
arr_int

array([[ 7,  8, 40,  9],
       [32, 24, 43, 27],
       [36, 35, 39, 10]])

# how to create random tensor using pytorch

In [ ]:
Tens = tc.rand(5)

In [ ]:
Tens

tensor([0.0108, 0.8404, 0.9436, 0.0949, 0.1311])

In [ ]:
Tens = tc.rand(3,4)

In [ ]:
Tens

tensor([[0.4375, 0.7617, 0.8765, 0.7862],
        [0.5521, 0.7139, 0.9817, 0.8608],
        [0.9165, 0.6628, 0.0215, 0.0458]])

In [ ]:
Tens_int = tc.randint(10, size = (2,3))

In [ ]:
Tens_int

tensor([[2, 3, 9],
        [8, 2, 1]])

In [ ]:
Tens_int = tc.randint(2,15, size = (2,4))

In [ ]:
Tens_int

tensor([[ 8, 12,  4,  5],
        [11,  8,  6,  9]])

# Numpy array Indexing, slicing and updating

In [ ]:
arr = np.random.randint(3,25, size = (3,5))

In [ ]:
arr

array([[24, 23, 23,  8, 17],
       [16, 13, 19,  4, 12],
       [ 3, 20,  4, 11, 18]])

In [ ]:
arr[0]

array([24, 23, 23,  8, 17])

In [ ]:
arr[0][4]

np.int64(17)

In [ ]:
arr[[0,1,2], [1, 2, 4]]

array([23, 19, 18])

In [ ]:
# updating the valuas with same value
arr[[0,1,2], [1, 2, 4]] =  23

In [ ]:
arr

array([[24, 23, 23,  8, 17],
       [16, 13, 23,  4, 12],
       [ 3, 20,  4, 11, 23]])

In [ ]:
# updating the values with different values for the each element

#way 1
arr[[0,1,2], [1, 2, 4]] = [12, 21,12]

In [ ]:
arr

array([[24, 12, 23,  8, 17],
       [16, 13, 21,  4, 12],
       [ 3, 20,  4, 11, 12]])

In [ ]:
#way 2

arr[[0,1,2], [2, 3, 0]] = (1, 4, 3)

In [ ]:
arr

array([[24, 12,  1,  8, 17],
       [16, 13, 21,  4, 12],
       [ 3, 20,  4, 11, 12]])

In [ ]:
#way 3

arr[[0,1,2], [3, 0, 1]] = 4,23,90

In [ ]:
arr

array([[24, 12,  1,  4, 17],
       [23, 13, 21,  4, 12],
       [ 3, 90,  4, 11, 12]])

In [ ]:
arr

array([[24, 12,  1,  4, 17],
       [23, 13, 21,  4, 12],
       [ 3, 90,  4, 11, 12]])

# Tensor Indexing, slicing and updating  using Pytorch

In [ ]:
Tens = tc.randint(3, 40, size = (4, 5))

In [ ]:
Tens

tensor([[16, 33, 36, 13, 24],
        [13, 26, 29,  6, 24],
        [32, 38, 24, 30, 31],
        [22, 16, 14, 15, 34]])

In [ ]:
type(Tens)

torch.Tensor

In [ ]:
Tens[0]

tensor([17, 24, 19, 11, 13])

In [ ]:
Tens[1][0]

tensor(14)

In [ ]:
Tens[[0,2,3] , [1, 0, 2]]

In [ ]:
Tens[[0,1,2]] = 1

In [ ]:
Tens

tensor([[ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1],
        [28,  6, 25, 12, 22]])

In [ ]:
Tens[[0,1,2], [0,2,1]] = 34  #here the 34 is the scalar right so it will broadcast to all the selected elements. so no nee to conver scalar value to tensor format.

In [ ]:
Tens

tensor([[34,  1,  1,  1,  1],
        [ 1,  1, 34,  1,  1],
        [ 1, 34,  1,  1,  1],
        [28,  6,  1, 12, 22]])

In [ ]:
Tens[[0,1,2], [1, 2, 4]] = [1,2,3]   #the list should be tensor format. then only the pytorch to assighn the values.. to each element

TypeError: can't assign a list to a torch.LongTensor

In [ ]:
Tens[[0,1,2], [1, 2, 4]] = tc.tendor([1,2,3]) # now it will assighn the values to the selected elements.

tensor([[16,  1, 36, 13, 24],
        [13, 26,  2,  6, 24],
        [32, 38, 24, 30,  3],
        [22, 16, 14, 15, 34]])

In [ ]:
Tens.dtype

torch.int64

In [ ]:
arr = np.array([1, 2, 3.4, "a"])   #numpy is allows to convert all the data types to uniform data type.

In [ ]:
arr

array(['1', '2', '3.4', 'a'], dtype='<U32')

In [ ]:
tens = tc.tensor([1,2, 4.3])  # both data type are numerical , so that torch is able to convert to uniform data type based on the priority.

In [ ]:
tens

tensor([1.0000, 2.0000, 4.3000])

In [ ]:
arr

array(['1', '2', '3.4', 'a'], dtype='<U32')

In [ ]:
tens = tc.tensor([1,2, 3.4, "a"])
'''in this example we have numerical and categorical(str) data type,  in torch is not supported to convert all the data types into string.
 when you have both numerical then it will convert, pytorch will work on gpu right! so it will work fast when we have numerical data. it's not allow string data type..'''

NameError: name 'tc' is not defined

#  Creating an numpy array using functions

In [ ]:
zeros = np.zeros(3)

In [ ]:
zeros

array([0., 0., 0.])

In [ ]:
zeros = np.zeros(2,4)

TypeError: Cannot interpret '4' as a data type

In [ ]:
zeros = np.zeros((2,4))

In [ ]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones = np.ones(3)

In [ ]:
ones

array([1., 1., 1.])

In [ ]:
ones = np.ones((2,3))

In [ ]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ex = np.eye(3)

In [ ]:
ex

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ex = np.eye(3,4)

In [ ]:
ex

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a = np.arange(2,8,1)

In [ ]:
a

array([2, 3, 4, 5, 6, 7])

# Creating an tensor array using functions

In [ ]:
Tens = tc.ones(3)

In [ ]:
Tens

tensor([1., 1., 1.])

In [ ]:
Tens = tc.ones(3,4)

In [ ]:
Tens

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
Tens = tc.zeros(3)

In [ ]:
Tens

tensor([0., 0., 0.])

In [ ]:
Tens = tc.zeros(3,5)

In [ ]:
Tens

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
Tens = tc.eye(3)

In [ ]:
Tens

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
Tens = tc.arange(2, 20,2)

In [ ]:
Tens

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
Tens = tc.zeros_like(input=tc.empty(3,4))

In [ ]:
Tens

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

**Tensor datatypes**

Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

Tensors not right datatype

Tensors not right shape

Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [ ]:
int_64 = tc.tensor((3,4),
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
int_64

tensor([3, 4])

In [ ]:
int_64.dtype

torch.int64

In [ ]:
int_64

tensor([3, 4])

**Type Casting**

In [ ]:
float_16_tensor = int_64.type(tc.float16)
float_16_tensor

tensor([3., 4.], dtype=torch.float16)

In [ ]:
float_16_tensor

tensor([3., 4.], dtype=torch.float16)

In [ ]:
t = tc.tensor([3.5, 5.6, 7.8])

In [ ]:
t.type(tc.int32)

tensor([3, 5, 7], dtype=torch.int32)

In [ ]:
t

tensor([3.5000, 5.6000, 7.8000])

In [ ]:
int_tens = t.type(tc.int32)

In [ ]:
int_tens

tensor([3, 5, 7], dtype=torch.int32)

**Getting information from tensors (tensor attributes)**

Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`

Tensors not right shape - to get shape from a tensor, can use `tensor.shape`

Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
Tens = tc.randint(10,50, size = (3,4))

In [ ]:
Tens

tensor([[27, 13, 40, 28],
        [13, 23, 22, 35],
        [47, 22, 38, 19]])

In [ ]:
Tens.dtype

torch.int64

In [ ]:
Tens.shape

torch.Size([3, 4])

In [ ]:
Tens.itemsize

8

In [ ]:
Tens.device

device(type='cpu')

**Manipulating Tensors (tensor operations)**

**Tensor opertions include:**

Addition

Subtraction

Multiplication (element-wise)

Division

Matrix multiplication


In [ ]:
tens = tc.tensor([1,2,3,4,5])

In [ ]:
tens

tensor([1, 2, 3, 4, 5])

In [ ]:
tens + 10

tensor([11, 12, 13, 14, 15])

In [ ]:
tens - 10

tensor([-9, -8, -7, -6, -5])

In [ ]:
tens * 2

tensor([ 2,  4,  6,  8, 10])

In [ ]:
tens_1 = tc.tensor([[1,2,3], [4,5,6]])

In [ ]:
tens_2 = tc.tensor([[4,3,2], [1,5,2]])

In [ ]:
tens_1 * tens_2

tensor([[ 4,  6,  6],
        [ 4, 25, 12]])

In [ ]:
tens_1.sum()

tensor(21)

In [ ]:
tens_1.sum(axis = 1) #row wise

tensor([ 6, 15])

In [ ]:
tens_1.sum(axis = 0)

tensor([5, 7, 9])

In [ ]:
tens_1.sub(tens_2)

tensor([[-3, -1,  1],
        [ 3,  0,  4]])

In [ ]:
tens_1.multiply(tens_2)

tensor([[ 4,  6,  6],
        [ 4, 25, 12]])

In [ ]:
tens_1.min(axis =1)

torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))

In [ ]:
tens_1.max(axis= 0).indices

tensor([1, 1, 1])

**Matrix multiplication**

Two main ways of performing multiplication in neural networks and deep learning:

Element-wise multiplication

Matrix mutliplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix mutliplication needs to satisfy:

The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

In [ ]:
tens_1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
tens_2

tensor([[4, 3, 2],
        [1, 5, 2]])

In [ ]:
tens_1.matmul(tens_2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
tens_2 = tens_2.reshape(3,2)

In [ ]:
tens_2

tensor([[4, 3],
        [2, 1],
        [5, 2]])

In [ ]:
tens_1.matmul(tens_2)

tensor([[23, 11],
        [56, 29]])

# Finding the positional min and max

In [ ]:
tens_1.argmax()

tensor(5)

In [ ]:
tens_1.argmin()

tensor(0)

**Reshaping, stacking, squeezing and unsqueezing tensors**

Reshaping - reshapes an input tensor to a defined shape

View - Return a view of an input tensor of certain shape
but keep the same memory as the original tensor

Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

Squeeze - removes all 1 dimensions from a tensor

Unsqueeze - add a 1 dimension to a target tensor

Permute - Return a view of the input with dimensions
permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
x.view(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x.reshape(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
arr = np.array([1,2,4], dtype = np.int32)

In [ ]:
arr

array([1, 2, 4], dtype=int32)

In [ ]:
arr.reshape(3,1)

array([[1],
       [2],
       [4]], dtype=int32)

In [ ]:
arr.view(np.float32)

array([1.e-45, 3.e-45, 6.e-45], dtype=float32)

In [ ]:
x = np.array([1, 2, 3], dtype=np.int32)
x_view = x.view(np.float32)  # Changes the data type
print(x_view)

[1.e-45 3.e-45 4.e-45]


1.e-45, 3.e-45, etc., are the bitwise representations of the integers 1, 2, and 3 when interpreted as float32 values.

int32 and float32 both use 4 bytes, but their interpretation of those bytes is different.

In [4]:
x = tc.tensor([[[1,2,3,4,5]]])

In [5]:
x

tensor([[[1, 2, 3, 4, 5]]])

In [6]:
x.reshape(5,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [7]:

# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x}")
print(f"Previous shape: {x.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[[1, 2, 3, 4, 5]]])
Previous shape: torch.Size([1, 1, 5])

New tensor: tensor([1, 2, 3, 4, 5])
New shape: torch.Size([5])


In [18]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1, 2, 3, 4, 5])
Previous shape: torch.Size([5])

New tensor: tensor([[1, 2, 3, 4, 5]])
New shape: torch.Size([1, 5])


In [13]:
x_unsqueezed = x_squeezed.unsqueeze(dim =0)

In [19]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [33]:
arr = np.array([1,2,3,4])

In [34]:
arr

array([1, 2, 3, 4])

In [35]:
Tens = torch.from_numpy(arr)

In [36]:
Tens

tensor([1, 2, 3, 4])

In [37]:
type(Tens)

torch.Tensor

In [38]:
# Change the value of array, what will this do to `tensor`?
arr = arr + 1
arr, Tens

(array([2, 3, 4, 5]), tensor([1, 2, 3, 4]))

In [39]:
Tens

tensor([1, 2, 3, 4])

In [40]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [42]:
# Change the tesnor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducbility (trying to take random out of random)**

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [43]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6558, 0.2657, 0.5928, 0.8680],
        [0.1181, 0.8315, 0.5627, 0.7973],
        [0.9994, 0.5850, 0.1820, 0.7103]])
tensor([[0.7511, 0.1828, 0.7948, 0.8870],
        [0.0762, 0.0253, 0.5448, 0.2385],
        [0.2727, 0.3546, 0.1923, 0.6529]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [44]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Running tensors and PyTorch objects on the GPUs (and making faster computations)**

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

**1. Getting a GPU**

Easiest - Use Google Colab for a free GPU (options to upgrade as well)
Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get:

https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/

Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them
For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation:
https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Tue Apr  8 06:50:11 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [3]:

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:

# Count number of devices
torch.cuda.device_count()


1

# 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [5]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#4. Moving tensors back to the CPU

In [7]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')