# Installing Numpy and Numpy Array Creation

In [ ]:
# Install a pip package in the current Jupyter kernel
! pip install numpy

In [2]:
#importing a numpy package
import numpy as np

In [2]:
lst=[1,2,3,4,5,"6"]
print(type(lst))
print("List:",lst)

<class 'list'>
List: [1, 2, 3, 4, 5, '6']


In [4]:
#Creating a simple array in numpy
arr=np.array(lst)
print(type(arr))
print(arr.itemsize)
print("NUmpy Array:",arr)  #ndarray is nothing but n dimentional array.

<class 'numpy.ndarray'>
44
NUmpy Array: ['1' '2' '3' '4' '5' '6']


In [5]:
arr1=np.array((1,2,3,4,5))
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [6]:
arr2=np.array({1,2,3,4,5})
print(type(arr2))
print(arr2)

<class 'numpy.ndarray'>
{1, 2, 3, 4, 5}


In [6]:
#creating ndarray  using arange function
rr=np.arange(10)
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# Why Numpy?

Most powerful numerical processing library in python. Array Oriented computing.

Provides extension package to python for multi dimensional array.

Very efficient.

Scientific computation.

# why numpy ,when we already have lists?

In [12]:
%%time
lst=list(range(1000000))
for i in  range(1000000):
    lst[i]*=lst[i]

CPU times: total: 203 ms
Wall time: 242 ms


In [13]:
%%time
arr=np.arange(1000000)
arr=arr*arr

CPU times: total: 0 ns
Wall time: 98.3 ms


# Attributes/Properties

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print("Shape:",arr.shape) #check the shape of the array. in the form of tuple
print("Data type:",arr.dtype)# data-type of array's elements.
print("Item size",arr.itemsize)#it returns the length of one arry element in bytes.
print("Dimentionalit",arr.ndim) #no.of dimentions present in the array.
print("size:",arr.size) # no.of elements present in the array. is aslo equal to np.prod(arr.shape)
print("total bytes",arr.nbytes)# returs the total bytes consumed by the elements of the array

[1 2 3 4 5 6]
Shape: (6,)
Data type: int32
Item size 4
Dimentionalit 1
size: 6
total bytes 24


In [4]:
ar=np.array([1,2,3,4,5])
print(ar.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [10]:
arr=np.array([[1,2,3,4],[5,6,7,8]]) #it will form the 2 dimentional array.
print("Array: \n",arr)
print("Shape:",arr.shape) #check the shape of the array. in the form of tuple
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)
print("size :",arr.size)
print(type(arr))

Array: 
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Data type: int32
Item size 4
Dimentionalit 2
size : 8
<class 'numpy.ndarray'>


In [29]:
arr=np.array([1,2.7,3,4.0,5]) # to convert the entaire elements into floate value
print(arr)
print(arr.dtype)
print(arr.itemsize)

[1.  2.7 3.  4.  5. ]
float64
8


In [30]:
arr=np.arange(1,10)
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [1 2 3 4 5 6 7 8 9]
Shape: (9,)
Data type: int32
Item size 4
Dimentionalit 1


In [31]:
arr=np.arange(1,10,2)
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [1 3 5 7 9]
Shape: (5,)
Data type: int32
Item size 4
Dimentionalit 1


**Another way to creating an numpy array using functions**

In [7]:
arr=np.ones((3))
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [1. 1. 1.]
Shape: (3,)
Data type: float64
Item size 8
Dimentionalit 1


In [17]:
arr=np.ones((3,3), dtype='i')
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (3, 3)
Data type: int32
Item size 4
Dimentionalit 2


In [11]:
arr=np.zeros((2,3))
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Shape: (2, 3)
Data type: float64
Item size 8
Dimentionalit 2


In [10]:
arr=np.zeros((3))
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [0. 0. 0.]
Shape: (3,)
Data type: float64
Item size 8
Dimentionalit 1


In [27]:
arr=np.eye((3)) # identity matrincs in mathmatics nothing but suqre matrix.
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape: (3, 3)
Data type: float64
Item size 8
Dimentionalit 2


In [22]:
arr=np.eye(3) # identity matrincs in mathmatics nothing but suqre matrix.
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape: (3, 3)
Data type: float64
Item size 8
Dimentionalit 2


In [28]:
arr=np.eye((3,3)) # identity matrincs in mathmatics nothing but suqre matrix.
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

TypeError: 'tuple' object cannot be interpreted as an integer

In [29]:
arr=np.eye(3,2) # identity matrincs in mathmatics nothing but suqre matrix.
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [[1. 0.]
 [0. 1.]
 [0. 0.]]
Shape: (3, 2)
Data type: float64
Item size 8
Dimentionalit 2


**type cast**

In [3]:
arr=np.array([1.,2.,3.4,4.])
print(arr)
print(arr.astype(int))

[1.  2.  3.4 4. ]
[1 2 3 4]


In [6]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.size)

10


In [35]:
arr=np.eye(3,2) # 3 rows and 2 colums
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [[1. 0.]
 [0. 1.]
 [0. 0.]]
Shape: (3, 2)
Data type: float64
Item size 8
Dimentionalit 2


In [42]:
arr=np.arange((10))
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Data type: int32
Item size 4
Dimentionalit 1


In [43]:
arr=np.arange(10)
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Data type: int32
Item size 4
Dimentionalit 1


In [44]:
arr=np.arange(10,20,2)
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

Array: 
 [10 12 14 16 18]
Shape: (5,)
Data type: int32
Item size 4
Dimentionalit 1


In [45]:
arr=np.arange((10,20,2))
print("Array: \n",arr)
print("Shape:",arr.shape)
print("Data type:",arr.dtype)
print("Item size",arr.itemsize)
print("Dimentionalit",arr.ndim)

TypeError: arange: scalar arguments expected instead of a tuple.

# Numpy Random Numbers

In [2]:
import numpy as np
arr=np.random.rand(5) #5 is represents the how money numbers you want to generate
print("Numpy array:",arr)

Numpy array: [0.45836141 0.29396344 0.22858982 0.9386465  0.54629978]


In [47]:
arr=np.random.rand(6,2) #10 rows and 2 colums
print(arr)

[[0.69914038 0.09385932]
 [0.64398744 0.55588757]
 [0.49826914 0.12972013]
 [0.85686736 0.35801575]
 [0.7054695  0.61221656]
 [0.38410493 0.2428714 ]]


In [4]:
arr=np.random.randn(5)
print(arr)

[ 1.08156912 -1.20173079  0.30189742 -1.09575759 -1.16836738]


In [49]:
arr=np.random.randn(5,4) #5 rows and 4 colums  
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[-1.62345065 -1.45941048  1.00257557 -1.46231023]
 [ 0.58557875 -0.39459757 -0.00616191 -0.18303994]
 [-0.17618729 -0.17309435 -0.21275169 -1.46739388]
 [ 1.01224834 -1.88262529 -0.87941202 -2.07736661]
 [-1.13446026  0.90264364  0.15337284 -0.35932379]]


In [48]:
#generate a random integer b/w 0 to 9
value = np.random.randint(10)
print(type(value))
print(value)

<class 'int'>
5


In [11]:
value = np.random.randint(10,31)
print(value)

20


In [12]:
#write a programm to creat a functionlity to similate of a dice roll ?

In [15]:
import numpy as np
def fun():
    dice_roll= np.random.randint(1,7)
    print("value:",dice_roll)
fun()

value: 2


In [ ]:
#write a programm to generate an otp(4 digit)

In [20]:
def otp():
    return np.random.randint(1000,10000)

In [21]:
otp()

2295

In [25]:
#randomly genarete a 5*4 array containing values
arr=np.random.randint(10, size=(5,4))
print(arr)

[[3 6 9 6]
 [5 0 6 8]
 [2 2 3 9]
 [9 8 5 5]
 [4 5 7 4]]


In [27]:
arr=np.random.randint(10,40, size=(5,4))
print(arr)

[[38 18 16 12]
 [26 35 37 35]
 [22 15 26 11]
 [11 19 24 28]
 [37 39 29 20]]


In [30]:
#generate random decimal value b/w 0 to 10
arr= np.random.uniform(10)
print(arr)

1.8943210216751663


In [33]:
arr=np.random.uniform(10, size=(5,4)) #b/t 0 to 10
print(arr)

[[9.86056048 8.7397809  5.75773791 1.33524321]
 [8.31302801 2.49616851 2.19463278 5.95443067]
 [6.62771659 3.90879502 6.60890953 4.50293908]
 [1.44937815 8.70664777 8.68706314 4.33279486]
 [7.11867449 4.74727365 7.91490295 9.69619112]]


In [34]:
arr=np.random.uniform(10,40, size=(5,4))  # 10 is minimum and 40 is maximum.
print(arr)

[[24.0465837  21.68061645 14.49624022 18.45942757]
 [21.29196336 26.4141793  34.06257224 12.74262845]
 [17.34293706 35.14864814 31.04422487 26.17854482]
 [33.38092093 30.31083838 15.99761631 37.34042386]
 [19.06610415 33.05534178 37.01865727 11.92431204]]


# Numpy array Indexing, slicing and updating

In [52]:
#randomly generating 1 dimentional array
arr=np.random.randint(100, size=(5,))
print(arr)
print(arr.shape)

[ 9 42 38  0 12]
(5,)


In [53]:
print(arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [39]:
print(arr[2])

62


In [41]:
print(arr[::-1])

[21 40 62  2 21]


In [19]:
#randomly generating 2 dimentional array
arr=np.random.randint(100, size=(5,4))
print(arr)

[[23 85 86 17]
 [89 76 91  3]
 [28 37 47 69]
 [ 6 81 80 39]
 [20 49 69 12]]


In [43]:
print(arr[2])

[35 69 49 80]


In [44]:
print(arr[1][2])

4


In [45]:
print(arr[1,2]) # [row_inde, col_inde]

4


In [47]:
print(arr[[1,3,4],[2,0,3]])

[ 4 72  5]


In [50]:
print(arr[1][2],arr[3][0],arr[4][3])

4 72 5


In [54]:
arr=np.random.randint(100, size=(10,))
print(arr)

[97 27 37 12 57  4 76 15 94 98]


In [55]:
arr

array([97, 27, 37, 12, 57,  4, 76, 15, 94, 98])

In [57]:
print(arr[:4])
print(arr[0:-4])
print(arr[::2])

[97 27 37 12]
[97 27 37 12 57  4]
[97 37 57 76 94]


In [25]:
arr=np.random.randint(100, size=(10,))
print(arr)

[20 34 56 81 59 22 13 14  5 36]


In [26]:
print(arr[1:4:-1])

[]


In [3]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
print(arr[:2,1:3])

[[2 3]
 [6 7]]


In [5]:
print(arr[1:3, :])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
print(arr[1:2, 2:3])

[[7]]


In [65]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [66]:
print(arr[0:2, 2:])

[[3 4]
 [7 8]]


In [67]:
print(arr[0:2,:3])

[[1 2 3]
 [5 6 7]]


**Indexing with boolean Arrays**

In [70]:
arr=np.random.randint(100, size=(10,))
print(arr)

[33 73 52 15 54 44 32 93 99 90]


In [71]:
idx=[True,False,False,False,False,True,False,False,True,True]
print(arr[idx])

[33 44 99 90]


**Updating value in the array**

In [8]:
arr=np.random.randint(100, size=(3,4))
print(arr)
arr[[1,2,0], [1,1,1]]=99
print("updated array:\n", arr)

[[83 79 23 90]
 [77 73 70 38]
 [28 97 85 61]]
updated array:
 [[83 99 23 90]
 [77 99 70 38]
 [28 99 85 61]]


In [3]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x*2)

[[ 2  4  6]
 [ 8 10 12]]


# Numpy Flatten and Ravel

In [3]:
import numpy as np
arr=np.random.randint(100, size=(5,10))
print(arr)
print("shape:",arr.shape)

[[ 6 38 58 34 65 13  6 71 74 57]
 [12 90 68  8 53 44 66 53  7 63]
 [ 1 70 85 40  3 45 37 88 77 34]
 [20 97 87 41 53 74 77 65 94 36]
 [63 18 97 18 87 79 74 60 80 69]]
shape: (5, 10)


In [4]:
flatten_arr=arr.flatten()
print(flatten_arr)
print(flatten_arr.shape)

[ 6 38 58 34 65 13  6 71 74 57 12 90 68  8 53 44 66 53  7 63  1 70 85 40
  3 45 37 88 77 34 20 97 87 41 53 74 77 65 94 36 63 18 97 18 87 79 74 60
 80 69]
(50,)


In [3]:
ravel=arr.ravel()
print(ravel)
print(ravel.shape)

[39 16 22 91 23  7 11 30 67 16  9 67 97 78 90 19 90 68 72 66 70 59 92  5
 65 52 62 53 50 57 19 79  3  3 83 72 37 87 46 15 91  2 40 98 53 41 43 79
 96 40]
(50,)


In [4]:
ravel[[0,1]]=10
print(flatten_arr)
print(ravel) #it effect to the original array.
print(arr)

[39 16 22 91 23  7 11 30 67 16  9 67 97 78 90 19 90 68 72 66 70 59 92  5
 65 52 62 53 50 57 19 79  3  3 83 72 37 87 46 15 91  2 40 98 53 41 43 79
 96 40]
[10 10 22 91 23  7 11 30 67 16  9 67 97 78 90 19 90 68 72 66 70 59 92  5
 65 52 62 53 50 57 19 79  3  3 83 72 37 87 46 15 91  2 40 98 53 41 43 79
 96 40]
[[10 10 22 91 23  7 11 30 67 16]
 [ 9 67 97 78 90 19 90 68 72 66]
 [70 59 92  5 65 52 62 53 50 57]
 [19 79  3  3 83 72 37 87 46 15]
 [91  2 40 98 53 41 43 79 96 40]]


**Iterating over Numpy Array**

In [3]:
import numpy as np
arr_1d=np.random.randint(10,40,size=(10,))
print(arr_1d)
print(arr_1d.shape)

[31 36 36 25 18 15 24 27 29 39]
(10,)


In [4]:
for i in arr_1d:
    print(i, end=" ")

31 36 36 25 18 15 24 27 29 39 

In [6]:
arr_2d=np.random.randint(10,40,size=(5,10))
print(arr_2d)
print(arr_2d.shape)

[[11 15 27 12 10 20 17 15 11 15]
 [10 31 13 12 18 23 27 35 38 21]
 [18 35 34 16 31 27 38 36 38 33]
 [22 39 35 35 38 19 31 33 13 33]
 [11 17 36 28 10 37 25 26 16 20]]
(5, 10)


In [7]:
for i in arr_2d:
    print(i)

[11 15 27 12 10 20 17 15 11 15]
[10 31 13 12 18 23 27 35 38 21]
[18 35 34 16 31 27 38 36 38 33]
[22 39 35 35 38 19 31 33 13 33]
[11 17 36 28 10 37 25 26 16 20]


In [8]:
for i in arr_2d.ravel():
    print(i, end=" ")

11 15 27 12 10 20 17 15 11 15 10 31 13 12 18 23 27 35 38 21 18 35 34 16 31 27 38 36 38 33 22 39 35 35 38 19 31 33 13 33 11 17 36 28 10 37 25 26 16 20 

**ndarray.flat**

1. **Flat:** The ndarray.flat attribute returns an iterator object that allows you to traverse the elements of the ndarray in a flattened manner, regardless of the original shape of the array. 
    ndarray.flat returns an iterator for traversing the elements of the ndarray without creating a new array. It provides a memory-efficient way to iterate over the elements.
    
2. **ndarray.flatten()** returns a new 1-dimensional array containing the flattened elements of the ndarray. It creates a new array and consumes additional memory.

Which one to use depends on your specific use case:

If you just need to iterate through the elements and don't need a separate array, **ndarray.flat** might be more memory-efficient.

If you need a separate flattened array for further computation, then using **ndarray.flatten()** is appropriate.

In [5]:
import numpy as np
arr=np.random.randint(10,40, size=(5,4))
flatten_arr=arr.flatten()
print(arr)
print(flatten_arr)
print(arr.flat[0]) # Flat is A 1-D iterator over the array.
print(arr[0])

[[27 21 32 30]
 [15 31 30 18]
 [22 38 26 36]
 [19 33 33 10]
 [39 37 15 17]]
[27 21 32 30 15 31 30 18 22 38 26 36 19 33 33 10 39 37 15 17]
27
[27 21 32 30]


In [7]:
import numpy as np
arr_2d=np.random.randint(10,40,size=(5,4))
ravel_arr=arr_2d.ravel()
for i in range(len(ravel_arr)):
    if (ravel_arr[i]% 2 !=0):
        ravel_arr[i]=-1
print("updated_array:\n", arr_2d)

updated_array:
 [[22 12 -1 32]
 [-1 -1 12 -1]
 [-1 12 32 -1]
 [26 -1 -1 36]
 [22 28 -1 28]]


In [13]:
np.zeros((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
arr = np.random.randint(100, size =(5,4))
print(arr)
flatten_arr = arr.ravel()
for i in range(len(flatten_arr)):
    count =0
    for j in range(2, flatten_arr[i]//2 +1):
        if flatten_arr[i]% j == 0:
            count +=1
    if count ==0:
            flatten_arr[i]=-1
print(arr)

[[50 43 36  7]
 [56 50 92  5]
 [97 16  1 94]
 [15 35 16 11]
 [46 38 53 51]]
[[50 -1 36 -1]
 [56 50 92 -1]
 [-1 16 -1 94]
 [15 35 16 -1]
 [46 38 -1 51]]


In [14]:
arr.flat=3
print(arr)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [5]:
arr.flat=3;arr

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [6]:
arr.flat[[1,4,6]]= 1
arr

array([[3, 1, 3, 3],
       [1, 3, 1, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

**if we what to assigning any value to the array , we can use flat.**

**Write a program to assign a value -1 if the element is odd number**

In [79]:
arr = np.random.randint(10,40, size=(5,5))
print("Origanal Array \n", arr)
print(arr.flat[[0,6,12,18,24]])

Origanal Array 
 [[37 27 38 36 32]
 [27 16 18 26 19]
 [16 12 31 33 15]
 [15 15 39 28 24]
 [28 39 27 21 25]]
[37 16 31 28 25]


In [81]:
arr[[1,2,3],[3,2,4]] =1

In [82]:
arr

array([[37, 27, 38, 36, 32],
       [27, 16, 18,  1, 19],
       [16, 12,  1, 33, 15],
       [15, 15, 39, 28,  1],
       [28, 39, 27, 21, 25]])

**write a program ,assign a value -1 at even place of an array**

In [1]:
import numpy as np
arr=np.random.randint(10,40, size=(5,4))
print("Numpy Array: \n", arr)
for i in range(5*4):
    if(i%2==0):
        arr.flat[i]=-1
print("Modified Array: \n", arr)

Numpy Array: 
 [[14 32 32 21]
 [29 29 11 26]
 [23 32 30 31]
 [14 20 23 25]
 [38 27 38 37]]
Modified Array: 
 [[-1 32 -1 21]
 [-1 29 -1 26]
 [-1 32 -1 31]
 [-1 20 -1 25]
 [-1 27 -1 37]]


In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [3]:
arr=np.random.randint(10,40, size=(5,4))
arr.flat[[2,4,6,8,10,12,14,16,18]]=-1
print(arr)

[[10 29 -1 25]
 [-1 37 -1 31]
 [-1 22 -1 19]
 [-1 31 -1 16]
 [-1 38 -1 11]]


**Numpy Reshape**

In [9]:
arr=np.random.randint(10,40, size=(5,10))
print(arr)
print(arr.shape)

[[11 19 38 27 20 37 24 31 38 31]
 [22 27 25 24 18 19 11 26 36 18]
 [31 12 19 17 29 23 34 33 30 10]
 [35 35 14 22 15 12 12 13 21 38]
 [18 33 19 21 21 37 18 25 22 12]]
(5, 10)


In [10]:
arr_reshape=arr.reshape(10,5)
print(arr_reshape)

[[11 19 38 27 20]
 [37 24 31 38 31]
 [22 27 25 24 18]
 [19 11 26 36 18]
 [31 12 19 17 29]
 [23 34 33 30 10]
 [35 35 14 22 15]
 [12 12 13 21 38]
 [18 33 19 21 21]
 [37 18 25 22 12]]


In [11]:
arr_reshape=arr.reshape(25,2)
print(arr_reshape)

[[11 19]
 [38 27]
 [20 37]
 [24 31]
 [38 31]
 [22 27]
 [25 24]
 [18 19]
 [11 26]
 [36 18]
 [31 12]
 [19 17]
 [29 23]
 [34 33]
 [30 10]
 [35 35]
 [14 22]
 [15 12]
 [12 13]
 [21 38]
 [18 33]
 [19 21]
 [21 37]
 [18 25]
 [22 12]]


**np.niter()**

In [11]:
arr=np.random.randint(10,40, size=(5,10))
for i in np.nditer(arr):
    print(i,end=" ")

19 10 20 33 16 21 16 26 15 31 24 17 19 14 26 31 28 30 20 30 31 25 33 35 36 28 39 22 19 11 30 36 25 26 15 20 29 21 23 16 21 34 34 29 14 30 22 33 26 18 

In [12]:
arr=np.random.randint(10,40, size=(5,10))
for i in np.nditer(arr):
    if i>20:
        i[...] = -1
print(arr)

ValueError: assignment destination is read-only

In [13]:
%%time
import numpy as np
arr=np.random.randint(10,40, size=(5,4))
print("Original Array: \n",arr)
for i in np.nditer(arr, op_flags=["readwrite"]):
    if i>20:
        i[...] = -1
print("Updated arry \n", arr)

Original Array: 
 [[13 19 13 39]
 [15 29 38 10]
 [11 34 16 36]
 [37 19 31 21]
 [20 14 24 19]]
Updated arry 
 [[13 19 13 -1]
 [15 -1 -1 10]
 [11 -1 16 -1]
 [-1 19 -1 -1]
 [20 14 -1 19]]
CPU times: total: 0 ns
Wall time: 8.01 ms


In [2]:
%%time
arr = np.random.randint(10,40, size=(5,4))
print("Origanal Array \n", arr)
for i in np.arange(5*4):
    if arr.flat[i] > 20:
        arr.flat[i]=-1
print("updated array: \n",arr)

Origanal Array 
 [[14 34 24 26]
 [39 32 24 14]
 [10 16 18 38]
 [13 33 38 26]
 [13 24 26 18]]
updated array: 
 [[14 -1 -1 -1]
 [-1 -1 -1 14]
 [10 16 18 -1]
 [13 -1 -1 -1]
 [13 -1 -1 18]]
CPU times: total: 0 ns
Wall time: 1 ms


In [3]:
%%time
arr_2d=np.random.randint(10,40, size=(5,4))
print("Original Array: \n",arr_2d)
for i in np.nditer(arr_2d, op_flags=["readwrite"]):
    if i%2 !=0:
        i[...] = -1
print("Updated arry \n", arr_2d)

Original Array: 
 [[11 35 22 37]
 [39 25 16 32]
 [29 16 32 17]
 [17 35 24 10]
 [34 27 11 21]]
Updated arry 
 [[-1 -1 22 -1]
 [-1 -1 16 32]
 [-1 16 32 -1]
 [-1 -1 24 10]
 [34 -1 -1 -1]]
CPU times: total: 0 ns
Wall time: 1.01 ms


In [31]:
import numpy as np
arr = np.random.randint(10,40, size=(5,4))
print("Numpy Array: \n", arr)
for i in range(5*4):
    if(i% 2 !=0):
        arr.flat[i] = -1
print("Modified Array: \n", arr)

Numpy Array: 
 [[25 20 29 20]
 [35 21 17 23]
 [12 21 32 25]
 [31 21 35 29]
 [13 25 35 25]]
Modified Array: 
 [[25 -1 29 -1]
 [35 -1 17 -1]
 [12 -1 32 -1]
 [31 -1 35 -1]
 [13 -1 35 -1]]


**Exercise: Given an array [1, -10, 2, 3, 0, 6], print the array in this order [0, 6, -10, 2, 1, 3]**

In [58]:
array = np.array([1, -10, 2, 3, 0, 6])
array.flat[[0,1,2,3,4,5]] = 0,6,-10,2,1,3
print(array)

[  0   6 -10   2   1   3]


In [29]:
arr= np.array([1, -10, 2, 3, 0, 6])
print(arr[[4,5,1,2,0,3]])

[  0   6 -10   2   1   3]


# Python Operators on NUmpy Array

In [15]:
arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [17]:
print(arr+4)

[[5 6]
 [7 8]]


In [37]:
print(arr*2)

[[2 4]
 [6 8]]


In [38]:
print(arr>=2)

[[False  True]
 [ True  True]]


In [39]:
print(arr %2==0)

[[False  True]
 [False  True]]


**Exercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Without Using a Loop)**

In [50]:
arr = np.random.randint(100, size=(5, 4))
print(arr)
a = arr % 2 !=0
if a.any() == True:
    arr[a] = -1
print("updated array: \n",arr)

[[59 31 72 74]
 [79 90 73 16]
 [59  7 19  0]
 [50  6  0 88]
 [21 31 90 65]]
updated array: 
 [[-1 -1 72 74]
 [-1 90 -1 16]
 [-1 -1 -1  0]
 [50  6  0 88]
 [-1 -1 90 -1]]


In [52]:
arr = np.random.randint(100, size=(5, 4))
print(arr)
a = arr % 2 !=0
arr[a] = -1
print("Updated Array: \n", arr)

[[32 57 14  2]
 [15 70 10  4]
 [92 99 87 73]
 [78 32 13 83]
 [41 74 98 65]]
Updated Array: 
 [[32 -1 14  2]
 [-1 70 10  4]
 [92 -1 -1 -1]
 [78 32 -1 -1]
 [-1 74 98 -1]]


# Ellipsis(...)

**Ellipsis(...):** expands to the number of (:)objects needed for the selection tuple to index all dimensions.
1. it is used for the to access the elements from the ndarray. 
2. it is also used for slicing consept

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[... , 0]

array(1)

In [38]:
arr = np.array([[1,2,3,4,5,6],[5,6,7,8,10,9],[12,13,14,15,17,18]])
print("array: \n",arr)
print(arr[... , 1])

array: 
 [[ 1  2  3  4  5  6]
 [ 5  6  7  8 10  9]
 [12 13 14 15 17 18]]
[ 2  6 13]


In [42]:
print(arr[:, 1])

[ 2  6 13]


In [48]:
print(arr[..., 4])

[ 5 10 17]


In [43]:
print(arr[:1,:])

[[1 2 3 4 5 6]]


In [38]:
print(arr[1, ...])

[ 5  6  7  8 10  9]


In [39]:
print(arr[1,:])

[ 5  6  7  8 10  9]


In [21]:
import numpy as np
arr =np.random.randint(100, size =(100, 100))
factor_num= (arr %5==0)  | ((arr%7 == 0) & (arr %2 !=0))
print(arr[factor_num])

[45 50 80 ... 55 75 85]


# Numpy Maths

In [55]:
print("Square root: ", np.sqrt(4))
print("Exponent: " , np.exp(1))
print("Trigonometric Sin: ", np.sin(0))
print("Trigonometric Cos:", np.cos(0))

Square root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos: 1.0


In [22]:
arr= np.array([1,2,3,4])
print("Square root: ", np.sqrt(arr))
print("Exponent: " , np.exp(arr))
print("Trigonometric Sin: ", np.sin(arr))
print("Trigonometric Cos:", np.cos(arr))

Square root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [46]:
# matrix multiplication
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x:\n", x)
print("y: \n", y)
print("Using matmul function: \n",np.matmul(x,y))
print("Using dot function: \n", np.dot(x,y))
print("Using @: \n",x @ y)

x:
 [[1 2]
 [3 4]]
y: 
 [[5 6]
 [7 8]]
Using matmul function: 
 [[19 22]
 [43 50]]
Using dot function: 
 [[19 22]
 [43 50]]
Using @: 
 [[19 22]
 [43 50]]


In [2]:
import numpy as np
arr =np.random.randint(10,40, size =(5,4))
np.where( arr %2 !=0, -1 , arr)

array([[-1, -1, 24, 12],
       [-1, 12, -1, -1],
       [-1, 20, 26, -1],
       [-1, -1, 12, -1],
       [-1, 12, 24, -1]])

In [25]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.cov(heights, weights)

array([[225.06666667, 199.46666667],
       [199.46666667, 225.46666667]])

# np.unique()

In [35]:
arr = np.array([[3,3],[3,3],[3,1]])
print("arr: \n", arr)
np.unique(arr)

arr: 
 [[3 3]
 [3 3]
 [3 1]]


array([1, 3])

In [36]:
print(np.unique(arr, axis =1))

[[3 3]
 [3 3]
 [1 3]]


In [37]:
print(np.unique(arr, axis=0))

[[3 1]
 [3 3]]


In [31]:
arr = np.array([[1,1],[1,1],[1,2]])
np.unique(arr, axis=1)

array([[1, 1],
       [1, 1],
       [1, 2]])

In [32]:
arr = np.array([1, 2, 6, 4, 2, 3, 2])
unique_values , index = np.unique(arr, return_index =True)
print(unique_values)
print(index)

[1 2 3 4 6]
[0 1 5 3 2]


In [40]:
arr = np.array([1,2,3,2,3])
u,inv = np.unique(arr, return_inverse= True)

In [41]:
u

array([1, 2, 3])

In [42]:
inv

array([0, 1, 2, 1, 2], dtype=int64)

In [44]:
u[inv]

array([1, 2, 3, 2, 3])

In [47]:
arr = np.array([1,2,3,4,5,2,3,4])
unique_val, counts = np.unique(arr, return_counts = True)

In [48]:
unique_val

array([1, 2, 3, 4, 5])

In [49]:
counts

array([1, 2, 2, 2, 1], dtype=int64)

In [52]:
# reconstruct the oroginal array using unique values and counts
np.repeat(unique_val, counts)

array([1, 2, 2, 3, 3, 4, 4, 5])

# np.in1d()

In [54]:
# if we want to find the arr2 of elements present in the arr1 or not
arr1 = np.array([1,2,4,5,6])
arr2 = np.array([1,2,3])
result = np.in1d(arr1, arr2)  #arr1 of elements present in the arr2.

In [55]:
arr1[result] 

array([1, 2])

In [56]:
result1 = np.in1d(arr1,arr2, invert= True)  #arr1 of elements not present in the arr1.

In [57]:
arr1[result1]

array([4, 5, 6])

In [58]:
import numpy as np
array = np.arange(4).reshape((2,2))
print(array)
array1 = np.array([0,1])
result = np.isin(array,array1)

[[0 1]
 [2 3]]


In [59]:
result

array([[ True,  True],
       [False, False]])

In [60]:
array[result]

array([0, 1])

In [61]:
result1 = np.isin(array, array1, invert =True)  # reverse operation i.e the list of elements not in the array.

In [62]:
result1

array([[False, False],
       [ True,  True]])

In [63]:
array[result1]

array([2, 3])

# numpy.setdiff1d

In [3]:
# find the unique values in arra1 that are not present in arr2.
import numpy as np
arr1 = np.array([1,2,3,4,5,2,4])
arr2 = np.array([3,4,5,6,7])
np.setdiff1d(arr1,arr2)

array([1, 2])

In [4]:
np.setdiff1d(arr2,arr1)

array([6, 7])

In [8]:
arr = np.arange(4).reshape(2,2)
print("array_1: \n",arr,)F
arr1 = np.array([[1,2],[4,5]])
print("array_2: \n", arr1)

array_1: 
 [[0 1]
 [2 3]]
array_2: 
 [[1 2]
 [4 5]]


In [9]:
np.setdiff1d(arr, arr1)

array([0, 3])

In [10]:
np.setdiff1d(arr1, arr)

array([4, 5])

# numpy.setxor1d

In [11]:
a = np.array([1,2,3,4,2,4])
b = np.array([2,4,5,6,5,7])
np.setxor1d(a,b)

array([1, 3, 5, 6, 7])

In [12]:
np.setxor1d(b,a)

array([1, 3, 5, 6, 7])

In [14]:
a1 = np.arange(4).reshape(2,2)
print("a1: \n",a1)
b1 = np.array([[2,3],[5,6]])
print("b1: \n",b1)
np.setxor1d(a1,b1)

a1: 
 [[0 1]
 [2 3]]
b1: 
 [[2 3]
 [5 6]]


array([0, 1, 5, 6])

# Numpy Maths

In [15]:
np.sqrt(4)

2.0

In [16]:
arr = np.array([1,2,3,4])

In [17]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [20]:
arr1 = np.array([[1,2],[3,4]])

In [21]:
np.sqrt(arr1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [22]:
np.exp(arr1)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [23]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [24]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [25]:
#element wise operations
x = np.array([[1,2],[3,4]])
y = np.array([[3,2],[4,6]])
print("Addition: \n", np.add(x,y))
print("Subtraction: \n", np.subtract(x,y))
print("Multiplication: \n", np.multiply(x,y))
print("Division: \n", np.divide(x,y))

Addition: 
 [[ 4  4]
 [ 7 10]]
Subtraction: 
 [[-2  0]
 [-1 -2]]
Multiplication: 
 [[ 3  4]
 [12 24]]
Division: 
 [[0.33333333 1.        ]
 [0.75       0.66666667]]


**3 ways to find the matrix multiplication**

In [32]:
x = np.array([[1,2],[3,4]])  #[(1*3 + 2*4) (1*2 + 2*6)
y = np.array([[3,2],[4,6]])   #(3*3 + 4*4)  (3*2 + 4*6)]
print(x)
print(y)
print("way 1: \n", np.matmul(x,y))
print("way 2: \n", np.dot(x,y))
print("way 3: \n", x@y)

[[1 2]
 [3 4]]
[[3 2]
 [4 6]]
way 1: 
 [[11 14]
 [25 30]]
way 2: 
 [[11 14]
 [25 30]]
way 3: 
 [[11 14]
 [25 30]]


In [33]:
#diagonal elements
x = np.array([[1,2,3],[4,5,6]])
np.diag(x)

array([1, 5])

In [34]:
#Transpose
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# NUMPY STATISTICS

In [38]:
x = np.array([1,2,3,4,5,123,45,76,89,231,56,90])
print("min_value: ",np.min(x))
print("max_value: ",np.max(x))
print("mean_value: ",np.mean(x))
print("std_value: ",np.std(x))
print("variant:", np.var(x))
print("median_value: ",np.median(x))

min_value:  1
max_value:  231
mean_value:  60.416666666666664
std_value:  65.63847745204197
variant: 4308.409722222222
median_value:  50.5


In [40]:
x = np.array([[1,2],[3,4]])
print("Sum :",np.sum(x))

Sum : 10


In [44]:
print("Sum :",np.sum(x,axis = 0))  #colum wise

Sum : [4 6]


In [46]:
print("Sum :",np.sum(x, axis = 1))

Sum : [3 7]


In [47]:
y = np.array([[2,4],[5,7]])
print(np.median(y, axis =0)) 
print(np.min(y, axis =1))

[3.5 5.5]
[2 5]


In [48]:
y = np.array([[2,4],[5,7]])
print(np.max(y, axis =0)) 
print(np.max(y, axis =1))

[5 7]
[4 7]


# Miscellaneous Topics

**linespace**

In [50]:
print(np.linspace(1,5,9))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [51]:
print(np.linspace(1,5,7))

[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.        ]


**sorting**

In [57]:
arr = np.random.randint(10,100, size = (4,4))
print(arr)

[[75 92 55 12]
 [49 41 69 84]
 [24 69 50 91]
 [22 77 60 69]]


In [58]:
np.sort(arr)

array([[12, 55, 75, 92],
       [41, 49, 69, 84],
       [24, 50, 69, 91],
       [22, 60, 69, 77]])

In [59]:
np.sort(arr, axis =0)

array([[22, 41, 50, 12],
       [24, 69, 55, 69],
       [49, 77, 60, 84],
       [75, 92, 69, 91]])

In [60]:
np.sort(arr, axis = 1)

array([[12, 55, 75, 92],
       [41, 49, 69, 84],
       [24, 50, 69, 91],
       [22, 60, 69, 77]])

**Stacking**

In [65]:
arr = np.arange(5,15).reshape(2,5)

In [66]:
arr

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
arr1 = np.arange(25,35).reshape(2,5)

In [69]:
np.vstack([arr,arr1])

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [67]:
arr+arr1

array([[30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [72]:
np.hstack([arr,arr1])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

**concatinating**

In [71]:
np.concatenate([arr,arr1], axis =0)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [73]:
np.concatenate([arr,arr1], axis =1)

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

**append**

In [76]:
np.append(arr,arr1, axis =0)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [78]:
np.append(arr,arr1, axis = 1)

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

# Numpy.where()

In [1]:
#syntax: np.where(condition, x,y) ,if condition is true than x return else y is return
#numpy where is appaly the broadcast application

In [2]:
import numpy as np
arr = np.random.randint(10,40, size= (5,4))
print("Array: \n", arr)
np.where((arr >30) &(arr < 38),0,1)

Array: 
 [[18 22 19 20]
 [23 21 18 28]
 [30 25 30 17]
 [26 25 10 27]
 [29 35 38 32]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 0, 1, 0]])

# Numpy Insert()

In [2]:
import numpy as np
arr = np.array([[1,2],[3,4],[7,8]])
np.insert(arr, 1,6, axis = 0)    # here 5 indic1ates the index, 6 is represent the inserted element at 5th position 0 is row wise

array([[1, 2],
       [6, 6],
       [3, 4],
       [7, 8]])

In [20]:
np.insert(arr, 1,6, axis = 1)  # 1 is indicates the colum wise.

array([[1, 6, 2],
       [3, 6, 4],
       [7, 6, 8]])

In [11]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [12]:
np.insert(a,5,6)

array([1, 1, 2, 2, 3, 6, 3])

In [23]:
print(arr)
np.insert(arr,[1],[[1],[2],[3]],axis =1) # if we want to insert at 1st position with diff values. axis= 1 means colums wise

[[1 2]
 [3 4]
 [7 8]]


array([[1, 1, 2],
       [3, 2, 4],
       [7, 3, 8]])

In [26]:
np.insert(arr,   1, [1, 2, 3], axis=1) #if we want to insert at 1st position with diff values. axis= 1 means colums wise

array([[1, 1, 2],
       [3, 2, 4],
       [7, 3, 8]])

In [27]:
np.array_equal(np.insert(arr,   1, [1, 2, 3], axis=1),
               np.insert(arr, [1], [[1],[2],[3]], axis=1))

True

In [31]:
np.insert(arr, slice(1,3),[0,0]) # here (1,3) are index positions and [0,0] are inserted at the 1 and 3 positions.

array([1, 0, 2, 0, 3, 4, 7, 8])

In [3]:
np.insert(arr, [1,3],[3.4,False])

array([18,  3, 22, 19,  0, 20, 23, 21, 18, 28, 30, 25, 30, 17, 26, 25, 10,
       27, 29, 35, 38, 32])

Question: Randomly generate a matrix of shape (1Million, 2) and perform below mentioned operations:

a. Find the distances between each 2-Dimensional data point from the centroid (i.e. mean) of the given dataset. Append the newly calculated distances as new column with the given dataset.

In [1]:
import numpy as np
arr = np.random.randint(100, size=(1000000,2))

In [2]:
#find the Centroid
centroid = np.mean(arr, axis =0)

In [3]:
#find the distence
dist = np.sum((arr - centroid)**2 , axis =1)
distance_midvalue = np.sqrt(dist)

In [14]:
stacking = np.hstack((arr, distance_midvalue.reshape([1000000, 1])))
print(stacking)

[[89.         90.         56.5702742 ]
 [49.         67.         17.49503122]
 [28.         33.         27.10228982]
 ...
 [33.         34.         22.64053081]
 [44.         35.         15.51622033]
 [40.         75.         27.19809092]]


Create an array of shape (1Million, 100). Write a function that takes Numpy array arr and returns a new array where each element represents the count of even elements in original array's row. 


In [14]:
import numpy as np
arr = np.random.randint(100, size =(1000000, 100))
even = arr %2 ==0
print("Original array: \n ", arr)
print("Total even numbers from each row of original array:")
np.sum(even, axis =1).reshape((1000000,1))

Original array: 
  [[62 77 77 ... 21 18 11]
 [73 26 91 ... 40 35 28]
 [90  4 36 ... 45 95 33]
 ...
 [75 73 19 ... 15 54 98]
 [79 44 67 ... 11 83 80]
 [37 39 21 ...  6 21 37]]
Total even numbers from each row of original array:
CPU times: total: 1.48 s
Wall time: 1.53 s


array([[54],
       [51],
       [46],
       ...,
       [55],
       [53],
       [42]])

**How to replace items that satisfy a condition without affecting the original array?**

In [17]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[1], [2]])
print(arr_1 + arr_2)

[[2 3 4]
 [6 7 8]]


In [5]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1])

print(arr_1 + arr_2)

[[2 3 4]
 [5 6 7]]


In [7]:
rr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)


[[2 4 6]
 [5 7 9]]


In [14]:
arr_1 = np.array([1, 2, 3, 4, 5])

arr_2 = np.array([1, 2, 3, 4])

print(arr_1 + arr_2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [15]:
arr_1 = np.array([[1], [2], [3], [4], [5]])
arr_2 = np.array([1, 2, 3, 4])
print(arr_2 + arr_1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
import numpy as np

In [5]:
arr = np.random.randint(10,50, size =(4,4))

In [6]:
arr

array([[11, 45, 31, 45],
       [33, 49, 23, 36],
       [44, 35, 48, 30],
       [12, 19, 40, 28]])

In [17]:
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if(arr[i][j]>40):
            print(arr[i])
            break

[11 45 31 45]
[33 49 23 36]
[44 35 48 30]


In [18]:
result = np.any(arr>40, axis =1)

In [20]:
arr[result]

array([[11, 45, 31, 45],
       [33, 49, 23, 36],
       [44, 35, 48, 30]])

# Numpy Basic Questions

**Write a Numpy program to get the Numpy version and show the Numpy build configuration.**

In [15]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.25.0
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

**2. Write a NumPy program to get help with the add function.**

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**3. Write a NumPy program to test whether none of the elements of a given array are zero.**

In [17]:
arr = np.array([1,2,3,4,5])
np.all(arr) #print(np.all(x)): This line uses the np.all() function to test if all elements in the array 'x' are non-zero (i.e., not equal to zero). In this case, all elements are non-zero, so the function returns True.

True

In [18]:
arr1 = np.array([[1,7,2,3,4],[1,2,3,4,5]])
np.all(arr1)

True

In [20]:
arr1 = np.array([[1,7,0,3,4],[1,1,1,1,1]])
print(np.all(arr1) ) # it takes by default 0 for the checking 
print(np.any(arr1))

False
True


In [21]:
np.all(arr1) ==1

False

In [22]:
np.any(arr1) ==1

True

**4. Write a NumPy program to test if any of the elements of a given array are non-zero.**

In [23]:
arr1 = np.array([[1,0,0,0,0],[0,0,0,0,0]])
np.all(arr1) !=0

False

In [24]:
np.any(arr1) !=0

True

**5. How to create a boolean array?**

In [25]:
np.zeros(10,dtype = bool).reshape(5,2)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [28]:
np.ones(10, dtype5 = bool).reshape(2,5)

TypeError: ones() got an unexpected keyword argument 'dtype5'

In [26]:
np.ones(10, dtype5 = bool).reshape(2,5)

TypeError: ones() got an unexpected keyword argument 'dtype5'

In [29]:
np.full((10), False, dtype = bool).reshape(5,2)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

**4. How to extract items that satisfy a given condition from 1D array?**

In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9])
odd = arr %2 !=0
arr[odd]

array([1, 3, 5, 7, 9])

**5. How to replace items that satisfy a condition with another value in numpy array?**

In [31]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [32]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where( arr %2 !=0, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**6. How to replace items that satisfy a condition without affecting the original array?**

In [33]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 =arr #or arr.copy()
print("Original array: \n",arr)
np.where(arr1 %2 !=0, -1, arr1)

Original array: 
 [[1 2 3 4]
 [5 6 7 8]]


array([[-1,  2, -1,  4],
       [-1,  6, -1,  8]])

**7. How to reshape an array?**

In [34]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
arr.reshape(2,-1)  # -1 represents the, it will tack  automatically how many colus are needed

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**8. How to stack two arrays vertically?**

In [38]:
arr = np.random.randint(10,40, size =(5,3))
print("arr: \n",arr)
arr1 = np.random.randint(10,40, size =(4,3))
print("arr1: \n",arr1)

arr: 
 [[26 31 33]
 [11 18 33]
 [36 13 33]
 [26 10 12]
 [16 13 15]]
arr1: 
 [[16 12 28]
 [30 22 24]
 [39 14 13]
 [17 21 39]]


In [39]:
np.vstack((arr,arr1))

array([[26, 31, 33],
       [11, 18, 33],
       [36, 13, 33],
       [26, 10, 12],
       [16, 13, 15],
       [16, 12, 28],
       [30, 22, 24],
       [39, 14, 13],
       [17, 21, 39]])

In [62]:
arr = np.array([3,8,2,6,10])
res= np.where(arr>5)[0]
print(res)
print(arr[res])

[1 3 4]
[ 8  6 10]


**8. How to stack two arrays horosontal?**

In [63]:
arr = np.random.randint(10,40, size =(5,3))
print("arr: \n",arr)
arr1 = np.random.randint(10,40, size =(5,2))
print("arr1: \n",arr1)

arr: 
 [[20 11 27]
 [32 31 16]
 [30 19 20]
 [14 34 17]
 [35 33 39]]
arr1: 
 [[16 13]
 [28 37]
 [24 28]
 [30 20]
 [35 36]]


In [64]:
np.hstack((arr,arr1))

array([[20, 11, 27, 16, 13],
       [32, 31, 16, 28, 37],
       [30, 19, 20, 24, 28],
       [14, 34, 17, 30, 20],
       [35, 33, 39, 35, 36]])

**10. How to generate custom sequences in numpy without hardcoding?**

In [42]:
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [43]:
arr = np.array([1,2,3])
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [44]:
np.tile(arr,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [45]:
np.hstack((np.repeat(arr,3),np.tile(arr,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [46]:
np.r_[(np.repeat(arr,3),np.tile(arr,3))]  #np.r_[] is represent he to concatenate the arrays row wise

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [47]:
np.vstack((np.repeat(arr,3),np.tile(arr,3)))

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [48]:
np.c_[(np.repeat(arr,3),np.tile(arr,3))]  #colum wise

array([[1, 1],
       [1, 2],
       [1, 3],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 1],
       [3, 2],
       [3, 3]])

**11. How to get the common items between two python numpy arrays?**

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

**12. How to remove from one array those items that exist in another?**

In [51]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
coman_values,index_x,index_y = np.intersect1d(x, y, return_indices=True)

In [52]:
#if we want to get the comman elements.
coman_values

array([5])

In [53]:
#if we want to get index of the common value from the array.
print("array__x:",index_x)
print("array__y",index_y)

array__x: [4]
array__y [0]


In [54]:
np.delete(x,index_x)

array([1, 2, 3, 4])

In [55]:
np.delete(y,index_y)

array([6, 7, 8, 9])

In [56]:
# we can also delete the common elements using set routes
np.setdiff1d(x,y)

array([1, 2, 3, 4])

In [57]:
np.setdiff1d(y,x)

array([6, 7, 8, 9])

**13. How to get the positions where elements of two arrays match?**

In [58]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

**14. How to extract all numbers between a given range from a numpy array?**

In [59]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
indx = np.where((a>=5) & (a<=10))
a[indx]

array([ 6,  9, 10])

In [60]:
a[np.where((a>=5) & (a<=10))]

array([ 6,  9, 10])

In [61]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
np.where(a>b, a,b)

array([6, 7, 9, 8, 9, 7, 5])

**16. How to swap two columns in a 2d numpy array?**

In [62]:
arr = np.arange(9).reshape(3,3)
print("Original array:\n", arr)

Original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
#column wise
arr[:,[1,2,0]]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

In [64]:
#row wise
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

**18. How to reverse the rows of a 2D array?**

In [65]:
arr = np.arange(9).reshape(3,3)
print("Original arra: \n", arr)
arr[2::-1,:]

Original arra: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [66]:
arr[:,2::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

**20. How to create a 2D array containing random floats between 5 and 10?**

In [68]:
arr = np.random.uniform(5,10,size=(5,3))
arr

array([[5.53271325, 9.20744984, 8.98686306],
       [9.55538953, 8.04608234, 5.39271765],
       [7.04150911, 7.3367421 , 7.02275346],
       [7.21501426, 9.21152936, 7.30128375],
       [7.1055894 , 7.85179056, 8.13057508]])

**21. How to print only 3 decimal places in python numpy array?**

In [1]:
import numpy as np
arr = np.arange(9)
np.set_printoptions(threshold=6)
arr

array([0, 1, 2, ..., 6, 7, 8])

**23.How to print the full numpy array without truncating**

In [2]:
np.set_printoptions(threshold=9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

**24. How to convert an array of arrays into a flat 1d array?**

In [3]:
arr = np.arange(3)
arr1 = np.arange(3,7)
arr2 = np.arange(3,9)
arr

array([0, 1, 2])

In [4]:
arr1

array([3, 4, 5, 6])

In [5]:
a = np.concatenate([arr,arr1,arr2])
a

array([0, 1, 2, ..., 6, 7, 8])

In [6]:
np.set_printoptions(threshold= 13)
a

array([0, 1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7, 8])

In [90]:
arr = np.array([2,5,1,6,10,4,8])
res = np.where(arr>5)[0]
print(res)

[3 4 6]


In [94]:
arr = np.array([[1,2,3],[4,5,6],[8,9,4]])
res = np.where(arr>=6)
print(arr[res])

[6 8 9]


In [95]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 4]])

In [96]:
print(res)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))
