# NUMPY

numpy stands for numerical python.
def:numpy is a python package for computation and processing of the multidimentional and single dimentional array elements.
1. it provides the exact amount of memory allocation
2. using numpy, onliy homogeneous data must be stored.
3. mathematical operations to be performed less code and more efficient compare to list.

**1.Attributes using Numpy**

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5]) #To create single dimentional array. and it aslo called 1D array/vector. is a simple list of elements
print(arr)

[1 2 3 4 5]


In [2]:
np.ndim(arr)   #returns the no.of dimentions of the arry

1

In [3]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
np.size(arr)

5

In [5]:
arr.T

array([1, 2, 3, 4, 5])

In [6]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])  # to create two dimentional array or 2D array/matrix
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
np.ndim(arr1)

2

In [8]:
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
np.size(arr1)

10

In [11]:
arr1.nbytes

40

In [12]:
arr1.dtype()

TypeError: 'numpy.dtypes.Int32DType' object is not callable

In [ ]:
arr1.dtype

In [ ]:
arr1.itemsize  #returns the size(in byte) of each element in the array.

In [ ]:
arr1.data

In [ ]:
arr1.T

In [ ]:
arr2=np.array([[[2,3],[4,5]],[[6,7],[8,9]]])   #to create n dimentional array
print(arr2)

In [13]:
arr2.reshape(4,2)

NameError: name 'arr2' is not defined

In [14]:
arr2.T   #returns the transpose of the array. (a new array with dimentions reversed)

NameError: name 'arr2' is not defined

In [15]:
arr2.real   #

NameError: name 'arr2' is not defined

In [16]:
arr2.imag

NameError: name 'arr2' is not defined

In [17]:
arr2.nbytes  #returns the total number of bytes consumed by the array

NameError: name 'arr2' is not defined

In [18]:
arr.nbytes

20

In [19]:
arr2.flatten()

NameError: name 'arr2' is not defined

In [20]:
s=arr2.flatten() #returns the 1-dimentional copy of the array.  if we try to modify the array using flatten() function . it will  not affected to the original
s

NameError: name 'arr2' is not defined

In [21]:
s[0]=10
print(s)

NameError: name 's' is not defined

In [22]:
arr2

NameError: name 'arr2' is not defined

In [23]:
s1=arr1.ravel()   #flattened viwe of the original array. if we try to modify the array using ravel() function . it will  be affected to the original array
s1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
s1[0]=10
s1

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr1

array([[10,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**statistical methods**

In [26]:
ar=np.array([1,2,3,4,10,23,28])

In [27]:
ar.max()

28

In [28]:
ar.min()

1

In [29]:
ar.mean()

10.142857142857142

In [30]:
ar.var()

103.26530612244899

In [31]:
ar.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [32]:
np.median(ar)

4.0

In [33]:
ar.argmin()   #returns the index of the minimum value in the array.

0

In [34]:
ar.argmax()  # returns the index of the maximum values in tha array.

6

In [35]:
np.cov(ar)

array(120.47619048)

# USE CASES IN DATA SCIENCE

**ATTRIBUTES AND STATISTICS FUNCTIONS**

**1.Data Exploration and Understanding**


1. **ndarray.shape:** Returns the dimensions of the array, providing information about the structure of the data.

2. **ndarray.ndim:** Returns the number of dimensions (axes) of the array, indicating whether the data is 1D,2D,o rhigher-  dimensional.

3. **ndarray.size:** Returns the total number of elements in the array, giving an idea of the dataset's size.

4. **ndarray.dtype:** Returns the data type of the elements in the array, helping to identify the nature of the data 
   (e.g., integers, floating-point numbers).

5. **ndarray.min():** Returns the minimum value in the array, providing an understanding of the lower bounds of the data.

6. **ndarray.max():** Returns the maximum value in the array, giving insights into the upper bounds of the data.

7. **ndarray.mean():** Calculates the mean (average) of the array, providing a measure of the central tendency of the data.

8. **ndarray.std():** Computes the standard deviation of the array, indicating the spread or dispersion of the data.

9. **ndarray.var():** Calculates the variance of the array, giving an understanding of the data's variability.

10. **ndarray.sum():** Computes the sum of all elements in the array, providing an aggregate value.

11. **ndarray.unique():** Returns the unique elements in the array, helping to identify distinct values in categorical or 
    discrete data.

12. **ndarray.argsort():** Returns the indices that would sort the array, allowing for the identification of the order or 
    ranking of elements.

These attributes can be utilized to explore and understand data by examining its shape, size, data types, range of values, 
central tendency, variability, and unique values. They provide useful information for gaining insights into the data 
distribution, detecting outliers, identifying patterns, and making initial observations about the dataset.

In [36]:
import numpy as np
arr=np.array([[1,2,3,4,5],[5,6,7,8,8]])
print(arr)

[[1 2 3 4 5]
 [5 6 7 8 8]]


In [37]:
arr.shape

(2, 5)

In [38]:
arr.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 5],
       [6, 7],
       [8, 8]])

In [39]:
arr.ndim

2

In [40]:
arr.size

10

In [41]:
arr.mean()

4.9

In [42]:
np.median(arr)

5.0

In [43]:
np.var(arr)

5.290000000000001

In [44]:
np.std(arr)

2.3000000000000003

In [45]:
arr.max()

8

In [46]:
arr.min()

1

In [47]:
arr.sum()

49

In [48]:
arr=arr+2
arr

array([[ 3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 10]])

In [49]:
arr.argmin()

0

In [50]:
arr.argmax()

8

In [51]:
arr.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [52]:
np.unique(arr)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

**2.handling missing values in data science**

In [53]:
import numpy as np

**np.abs() --->** calculate the absolute value element-wise

In [54]:
s=np.array([1,2,3,-4,5])
s.abs()
print(s)

AttributeError: 'numpy.ndarray' object has no attribute 'abs'

In [55]:
s=np.array([1,2,3,-4,5])
print(np.abs(s))

[1 2 3 4 5]


In [56]:
a=np.absolute([1,5,-3,4,2])
print(a)

[1 5 3 4 2]


In [57]:
a.sort()
a

array([1, 2, 3, 4, 5])

**np.arange() **---> can be called with a varying number of positional arguments and returns the spaced values within a given interval

In [58]:
b=np.arange(3)
print(b)

[0 1 2]


In [59]:
c=np.arange(4)
c

array([0, 1, 2, 3])

In [60]:
print(c)

[0 1 2 3]


In [61]:
d=np.arange(-4)
print(d)

[]


In [62]:
e=np.arange(-4,0,1)
print(e)

[-4 -3 -2 -1]


In [63]:
f=np.arange(0,-4,-1)
print(f)

[ 0 -1 -2 -3]


In [64]:
g=np.arange(10,0,-1)
print(g)

[10  9  8  7  6  5  4  3  2  1]


In [65]:
h=np.arange(0,11,1)
print(h)

[ 0  1  2  3  4  5  6  7  8  9 10]


1. **ndarray.argsort()**: Returns the indices that would sort the array, allowing for the identification of the order or ranking of elements.

2. **np.unique()**: Returns the unique elements in the array, helping to identify distinct values in categorical or discrete data.

3. **np.concatenate()**: Concatenates two or more arrays along a specified axis, allowing you to combine arrays together.

4. **np.split()**: Splits an array into multiple sub-arrays along a specified axis, enabling data partitioning.

5. **np.random.random()**: Generates random numbers from a uniform distribution between 0 and 1, useful for generating random data or sampling.

6. **np.random.randn()**: Generates random numbers from a standard normal distribution, useful for generating random data with mean 0 and standard deviation 1.

These basic NumPy methods and attributes play a vital role in data manipulation, aggregation, summary statistics, sorting, indexing, and generating random data. They provide a foundation for many data science operations and are widely used in data analysis, preprocessing, and modeling tasks.

In [66]:
arr=np.array([1,2,3,4,5,1,6,7,1])
x=np.argsort(arr)
print(x)

[0 5 8 1 2 3 4 6 7]


In [67]:
y=np.argmax(arr)  # it returns the highest index of the array element.
print(y)

7


In [68]:
z=np.argmin(arr)  #it returns the fist index of the array element.
print(z)

0


In [69]:
w=np.argwhere(arr>1)  # it returns the indeces of the array elements.and it deosn't returns the duplicate elements of 
                     # the indeces. in arr, 1 is repeating 3 times , in this example it retuns the except "1"  of the indeces.
print(w)                  

[[1]
 [2]
 [3]
 [4]
 [6]
 [7]]


In [70]:
v=np.argwhere(arr)
print(v)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [71]:
u=np.argwhere(arr>2)
print(u)

[[2]
 [3]
 [4]
 [6]
 [7]]


In [72]:
t=np.unique(arr)  #returns the unique values and ignore the duplicate elements.
print(t)

[1 2 3 4 5 6 7]


In [73]:
arr1=np.array([8,9,10])
s=np.concatenate(arr,arr1)
print(s)

TypeError: only integer scalar arrays can be converted to a scalar index

In [74]:
arr1=np.array([8,9,10,11])      # concatenate the two arrays.
s=np.concatenate((arr,arr1))
print(s)

[ 1  2  3  4  5  1  6  7  1  8  9 10 11]


In [75]:
r=np.split(arr) #Splits an array into multiple sub-arrays along a specified axis
print(r)  

TypeError: split() missing 1 required positional argument: 'indices_or_sections'

In [76]:
r=np.split(arr1,2)  
print(r)

[array([8, 9]), array([10, 11])]


In [77]:
r=np.split(arr1,3)  # in arr1, it contains the 4 elements it can't split the 4 elements into sub array of 3 elemnts.
print(r)

ValueError: array split does not result in an equal division

In [ ]:
q=np.random.random()
print(q)

In [ ]:
q=np.random.random(arr1)
print(q)

In [ ]:
p=np.random.randn()
print(p)

**np.zeros()**: Returns an array filled with zeros of a specified shape.

**np.ones()**: Returns an array filled with ones of a specified shape.
    
**np.eye()**: Returns a 2D identity matrix of a specified size.

**np.linspace()**: Returns an array of evenly spaced values within a specified range.

In [83]:
arr2=np.array([1,2,3])
o=np.zeros(arr2).reshape(2,4)
print(o)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [84]:
arr2=np.array([1,2,3])
o=np.zeros(arr2).reshape(2,3)
print(o)

[[0. 0. 0.]
 [0. 0. 0.]]


In [85]:
n=np.eye(2)   
n

array([[1., 0.],
       [0., 1.]])

In [86]:
print(n)

[[1. 0.]
 [0. 1.]]


In [87]:
m=np.eye(3)   #Return a 2-D array with ones on the diagonal and zeros elsewhere.
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
l=np.eye(4)   #Return a 2-D array with ones on the diagonal and zeros elsewhere.
print(l)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**np.linspace(start,stop)**

In [89]:
k=np.linspace(10,1,-1)
print(k)

ValueError: Number of samples, -1, must be non-negative.

In [90]:
k=np.linspace(1,3)
print(k)

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]


**np.prod()** 

In [91]:
print(np.prod(arr2))  #it returns the product of elements in the array

6


In [92]:
arr2.sum()  # it returns the sum of elements in araay and 

6

In [93]:
arr2.cumsum()   # it returns the cumulative sum of array elements 

array([1, 3, 6])

In [94]:
arr2.sum()   # it returns the  sum of array elements 

6

In [95]:
arr2.cumprod()  ## it returns the cumulative product of array elements 

array([1, 2, 6])

In [97]:
arr2

array([1, 2, 3])

In [98]:
arr3=np.array([2,3,4])
print(np.dot(arr2,arr3))   #np.dot()---> returns the dot product of two numbers. here, arr2[0]*arr3[0] +arr2[1]*arr3[1]+...

20


In [100]:
print(np.isnan(arr3))   #it checks the if the array contains the NAN(not a number) or not. if it contains NAN it returns "true", else it returns "false"

[False False False]


In [1]:
import numpy as np

In [ ]:
np.